### ISSUE TITLE
Total Energy only increases in steps of 10

### ISSUE THREAD

**Issue by cvroque** [hultenvp/solis-sensor#198] opened 2022-11-06 11:49 UTC
**Describe the bug**

Ever since a few days ago, the integration stopped increasing the energy total immediately and instead is just increasing it in steps of 10:

![image](https://user-images.githubusercontent.com/65680394/200168633-608df226-1e4e-4a56-b2ac-2bdb6899fe9e.png)

It seems to have changed on November 3, I also have the latest updates installed. Anyone else having the same problem?

**Config**
UI configuration

**Versions**
Home Assistant 2022.11.1 on HA OS x86
HACS version: 1.28.3
Integration version: v3.0.8

**Screenshots**

Many steps on Nov 3:

![image](https://user-images.githubusercontent.com/65680394/200168813-bd7c5bb1-5cab-4701-aa04-0819f90729ab.png)

And after that, only increases of 10.

**Comment by hultenvp** [comment] 2022-11-06 13:12
Can you add debug logs?
Are you using the Ginlong platform or the soliscloud?

**Comment by cvroque** [comment] 2022-11-07 17:35
> Can you add debug logs?
> Are you using the Ginlong platform or the soliscloud?

Hello! I'm using the soliscloud and below are the the logs. I also noticed the daily and monthly energy is increasing normally, while total and year are in steps of 10:
![image](https://user-images.githubusercontent.com/65680394/200367039-82f100e9-7473-4e35-a1d7-e3f023ad71b7.png)

After checking, I believe it is an API change.

[DEBUG LOGS.txt](https://github.com/hultenvp/solis-sensor/files/9954070/text_53.txt)

**Comment by hultenvp** [comment] 2022-11-10 21:27
My panels don't receive much sunlight lately, but today I collected enough energy to see indeed  energy_total making a 10 kWh step. So confirmed, this is how the API now apparently reports it.

**Comment by hultenvp** [comment] 2022-11-10 21:27
Closing as not a bug

**Closed by hultenvp** 2022-11-10 21:27 UTC
Labels: bug
