### ISSUE TITLE
Wrong data in the morning energydashboard

### ISSUE THREAD

**Issue by mwitlox** [hultenvp/solis-sensor#91] opened 2022-02-07 10:44 UTC
**Describe the bug**
Wrong data in the morning energydashboard

**Config**
Solarman portal config m.ginlong.com (Solis inverter, Wifi dongle) not yet migrated

**Versions**
HA Version 2022.x
HACS version last 2 versions. Now 1.22.0
Integration version v2.0.6

**Debug logs** < Will do this when needed
Add to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
And attach the resulting log to the issue. If yo do not know where to find logs you missed an important step in the install of HACS. ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/96582378/152773216-a4c91f49-b5d7-4b13-87e1-5e7e60156cba.png)

**Comment by mwitlox** [comment] 2022-02-07 12:54
Tried redownloading, reconfigure, readd in energy dashboard

**Comment by hultenvp** [comment] 2022-02-07 19:14
Hi @mwitlox, not sure from your last comment if the problem is now solved or actually happening on both platforms?
If the problem still exists; could you let me know how many minutes wide the spike is? Hovering over the spike with mouse shows timestamps

Thanks

**Comment by mwitlox** [comment] 2022-02-07 19:23
Hi @hultenvp. Sorry for that. Both portals are working. I still use the m.ginlong.com portal and your program to get the data to HA. Haven't tried the new portal with your program. Maybe better to use the new portal?

Today 8:17:48 - 8:19:50

04/02/2022 same thing but then 8:42:09 - 8:44:10

**Comment by hultenvp** [comment] 2022-02-07 20:35
Not sure if using the other portal will help. The person that helped me with the support of soliscloud is seeing other issues, so switching might mean you trade one issue for another ;-)
I still have one improvement I can make. I'm going to test that it doesn't break anything and if it works I will drop the release later this week.

**Comment by LucidityCrash** [comment] 2022-02-08 10:16
Its worth noting here that my data is available in both systems also

I have a Hybrid inverter with a battery so it never actually goes offline ... The Daily figures sometimes don't reset at midnight but a few seconds/minutes after - on m.ginlong.com that totally breaks the energy use for the day until the next day or until the amount used today exceeds the amount used yesterday.
On soliscloud it fixes itself the next reading but I've yet to switch over to using the soliscloud data to drive my energy dashboard so not sure how it will affect that.

I've found some data inconsistancies in the SolisCloud website and API ... on the website my "Daily energy to grid" and "Daily energy from grid" are always 0 even though the "Total energy to grid" and "Total energy from grid" are increasing.  However the API returns both the correct "Total energy from grid" AND "Daily energy from grid" but NOT the correct "Daily energy to grid" OR "Total energy to grid".  If I look at what the m.ginlong.com shows the "Daily energy to grid" does sometimes show a very little (like 0.1 kWh) and the "Daily energy from grid" is always non zero so the data is there in the backend it just isn't available via SolisCloud for some reason.  I've currently got tickets open with Solis Support but for the Daily energy to grid one they are saying that the export is so low that it is rounding down and hence not showing and to stop wasting their time ... for the daily energy to grid and the reset to 0 at midnight they are just not answering.

**Comment by hultenvp** [comment] 2022-02-08 13:31
Hey @LucidityCrash ,

From our discussion I understood you had issues on the ginlong portal itself, but the way I understand now you actually have issues with the integration messing up your energy dashboard, because energy today rests to 0 after midnight instead of at midnight?

**Comment by LucidityCrash** [comment] 2022-02-08 14:33
no you were correct it is the data stored in m.ginlong.com that is broken ... when I use the SolisCloud API it works much better.

I assume the issue is down to timing the datalogger sends data every 5 minutes (ish) so today for example the first value is reported as being at 00:00:19 but however the reset is worked out the numbers that it has stored in the backend haven't been reset to zero at this point.

for exaple on m.ginlong.com if yesterday I used 15kWh but that isn't reset till after midnight then today it will say 15kWh until I've used 15.1 kWh ... this screws up the energy dashboard but it is only because the data coming in is bad.  With the SolisCloud API when the data resets to 0 after midnight it actually does reset.

m.ginlong.com api :
![image](https://user-images.githubusercontent.com/49124523/152999189-90c85b20-11df-4ecd-b53d-7371a1b0d572.png)

SolisCloud api : 
![image](https://user-images.githubusercontent.com/49124523/152999244-3a127cda-dafc-4182-8a26-48b371c65161.png)

Looks like the Daily Yield on this one didn't reset till after midnight on SolisCloud either

**Comment by hultenvp** [comment] 2022-02-08 20:52
Indeed, with normal battery-less inverters the daily energy is reset at inverter power-up in the morning. For you, with battery it is reset somewhere just after midnight.
I think I can fix both scenarios. Pretty sure I have @mwitlox case fixed now (cannot reproduce myself, but should be okay). Going to give your scenario a try as well by ignoring any energy today data from the server the first 15 minutes of a day and just return '0'. 
Will run regression test tomorrow, if all passes will release later this week.

**Comment by LucidityCrash** [comment] 2022-02-09 14:43
15 mins seems excessive ... its never going to be more than 5 mins late resetting (this is on SolisCloud ... m.ginlong.com never resets).

**Comment by mwitlox** [comment] 2022-02-10 09:31
A bit more info. Seems to happen every 3 days. Today 8:37:19 - 8:39:11 same thing.

Total value of the day before is given to HA. Then a bit later the total resets en starts counting from 0. But the energy dash stores the value of the day before + counting the new day from the beginning

Maybe this will make things a bit more clear. Screenshots from this morning

![Schermafbeelding 2022-02-10 101935_Solos](https://user-images.githubusercontent.com/96582378/153376727-4b9a1a83-9972-470a-a593-b4fc6e0ea90d.jpg)
Time 00:01:15
![Schermafbeelding 2022-02-10 101955_Solis 2](https://user-images.githubusercontent.com/96582378/153376747-c0807741-583c-42ab-890c-766fe0971de6.jpg)
![Schermafbeelding 2022-02-10 102027_Solis 3](https://user-images.githubusercontent.com/96582378/153376759-b7c7f85b-2509-4d7c-aa08-e7b3201816fe.jpg)

Another thing, because the Wifi module is powering on-off-on-off-on... maybe that is also a problem. Here a screenshot from my P1 DSMR Production
![Schermafbeelding 2022-02-10 102502_Solis 4](https://user-images.githubusercontent.com/96582378/153377537-faf173e1-e604-4e36-91ac-cc336fb12a1e.jpg)

**Comment by hultenvp** [comment] 2022-02-10 12:00
I just release v2.0.7.

Looking at all the data you shared this should fix the issue.
It also should address the issue of @LucidityCrash .

Let me know if it works.

**Comment by hultenvp** [comment] 2022-02-11 11:54
Was it better this morning?

**Comment by attila123456** [comment] 2022-02-11 12:22
I had the same issue, this morning was all good!

**Comment by mwitlox** [comment] 2022-02-11 12:27
![2022-02-11_13-17-50_Solis 1](https://user-images.githubusercontent.com/96582378/153590873-59162a38-9c20-403c-a0e1-c207240f3842.png)
![2022-02-11_13-17-08_Solis 2](https://user-images.githubusercontent.com/96582378/153590882-c67566a7-875b-4c60-a6e1-8a7cc75b7723.png)

This morning a normal fresh start :)!

I will watch is for a couple of days because the issue was every 3 days. But i think it's all good now!

@hultenvp good job 🥇 !

**Comment by bckmrk** [comment] 2022-02-11 12:52
I had some weird notch in the diagram this morning. It was cloudy and a slow start resulted in this behavior

![image](https://user-images.githubusercontent.com/84834650/153593872-fcce5d6d-4543-466b-b46a-fc77d876afc1.png)

Close up:

![image](https://user-images.githubusercontent.com/84834650/153594449-29a5468b-2455-4f0c-8e37-ed36e0469ab7.png)

Looks like multiple resets?

**Comment by hultenvp** [comment] 2022-02-11 13:24
@bckmrk : If it were multiple resets then it should be visible in inverter state. You should see toggles between state value 1 and 2 then.

I sometimes feel some ginlong employee is monitoring me and figuring out ways how they can complicate stuff further 🤣

**Comment by bckmrk** [comment] 2022-02-11 13:34
Don't see that. Don't know what it was.. 

![image](https://user-images.githubusercontent.com/84834650/153600477-1fa2feae-1a45-4ec4-905a-2c170e03cc72.png)

**Comment by hultenvp** [comment] 2022-02-11 14:04
You had some interrupts of service around that time:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/61835400/153605369-a4404b40-893d-4abb-b0b0-121a5f177ec2.png">

**Comment by bckmrk** [comment] 2022-02-11 14:24
wow, didnt notice.

**Comment by hultenvp** [comment] 2022-02-12 13:54
Closing based on feedback that the fix works

**Closed by hultenvp** 2022-02-12 13:54 UTC
Labels: bug
