### ISSUE TITLE
Incorrect Power conversion

### ISSUE THREAD

**Issue by henrikeri** [hultenvp/solis-sensor#85] opened 2022-02-02 10:55 UTC
**Describe the bug**
Power generation shows 2.6 W while it's in fact 2.6 kW. Seems to happen when generation > 1kW

**Config**
Default config, no changes. Using m.ginlong.com

**Versions**
HA Version an deployment: core-2022.2.0b6 on HA OS 7.2
HACS version: 1.21.0
Integration version: 2.0.4

**Screenshots**
Upper inverter:
![image](https://user-images.githubusercontent.com/35510093/152141121-77f0e2dd-c8ec-4d8c-ba81-95921b6f1e66.jpeg)
Lower right gauge:
![image](https://user-images.githubusercontent.com/35510093/152140601-62897c9e-2ab2-4900-b400-16e997dec0f8.png)

**Comment by hultenvp** [comment] 2022-02-02 14:37
Hey @henrikeri, thanks for reporting. This is a duplicate of issue #56 . There's actually a link to a fix in that issue. It's under test by the submitters in that issue. Happy if you try it out as well.

Cheers

**Comment by henrikeri** [comment] 2022-02-02 22:43
@hultenvp 
Thanks I've added the latest api file. Hopefully we'll have nice enough weather for a test tomorrow.

Cheers :)

**Comment by hultenvp** [comment] 2022-02-03 07:25
Thanks, make sure you copied the changed file into a v2.0.5 release. This to avoid mixing versions.

**Comment by kazikskrz** [comment] 2022-02-03 10:54
sensor.inverter_ac_output_total_power shows 1,02 W instead of 1,02 Kw

**Comment by hultenvp** [comment] 2022-02-04 10:32
Fixed in v2.0.6, let me know if you still experience issues

**Closed by hultenvp** 2022-02-04 10:32 UTC
Labels: bug, duplicate

**Comment by etzka** [comment] 2022-02-04 12:17
> Fixed in v2.0.6, let me know if you still experience issues

it worked fine for me in version v2.0.5. Above 1kw showed good in watts

**Comment by hultenvp** [comment] 2022-02-04 12:50
@etzka : Thanks for the screenshot, so working fine it seems!

**Comment by kazikskrz** [comment] 2022-02-07 09:30
Looks good to me now. Many thanks for quick fix.
